name: Deployment
run-name: "Deployment started by @${{github.actor}}"
on:
  workflow_dispatch:
  #push:
  #  branches: [main]
    
jobs:      
  test:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm test
      
  deploy:
    #needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Pulling update on remote machine
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          # port: ${{ secrets.DEPLOY_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /app/frontend
            git stash
            git checkout main
            git pull origin main
            npm install
            npm run build
      
